export * from './Avatar';
export * from './Navbar';
export * from './ThemeSwitch';
export * from './Name';
export * from './Profession';
export * from './ContactDetails';
export * from './Box';
export * from './Education';
export * from './Capsule';
